#!/usr/bin/env php
<?php

use Stratum\Original\Autoloader\Autoloader;
use Stratum\Original\CommandLine\Command\CompileCSS;
use Stratum\Original\CommandLine\Command\CompileJs;
use Stratum\Original\CommandLine\Command\CompileViewsCommand;
use Stratum\Original\CommandLine\Command\CreateCommand;
use Stratum\Original\CommandLine\Command\ExportStyle;
use Stratum\Original\CommandLine\Command\FinishInstallationCommand;
use Stratum\Original\CommandLine\Command\FixFiles;
use Symfony\Component\Console\Application;

require_once 'Bootstrap.php';

$application = new Application();

$application->add(new CompileViewsCommand);
$application->add(new FinishInstallationCommand);
$application->add(new CreateCommand);
$application->add(new FixFiles);


$application->run();